### ISSUE TITLE
Refresh Token Null in V2-Beta

### ISSUE THREAD

**Issue by amasta** [auth0/Lock.Android#336]
I am using v2 of Lock and never receive a refresh token unless I specifically add a scope for offline access. This is confusing because in V1 this was fixed. (See issue #52). Here is my setup of Lock.

```
    Map<String, Object> params = ParameterBuilder.newAuthenticationBuilder()
            .asDictionary();

    mLock = Lock.newBuilder(auth0, lockCallback)
            .withTheme(customizedLockTheme)
            .withAuthenticationParameters(params)
            .build();
    mLock.onCreate(mContext);
```

**Comment by hzalaz** [comment]
In v1 it was fixed since we documented the default scope was `openid offline_access`, since v2 is a new major we are still ironing details and thinking what the default should be. Now the default is just `openid` and probably will remain that way. We'll review the docs to make it clear what the default is.
