### ISSUE TITLE
Issue with setting scope.

### ISSUE THREAD

**Issue by zfort-vitalii** [auth0/Lock.Android#428]
Hello,
i catch an issue with scope. 
I use passwodless auth. When try to add “profile” scope it return an error.

Here is two ways that i use for setting up scope. Also want to notice that without setting scope all works perfectly.

Code of initing a lock :
   ```
        Map<String, Object> params= new HashMap<>();
//        params.put("scope", "openid profile");
        PasswordlessLock mLock = PasswordlessLock.newBuilder(auth0, mCallback)
                .withAuthenticationParameters(params)
                .withAuthButtonSize(AuthButtonSize.SMALL)
                .useLink()
                .closable(true)
                .build(this);
//        mLock.getOptions().withScope("openid profile");
```
 url=https://droneup-dev.auth0.com/oauth/ro
code=401,
 message=,

Error body from okhttp 
```
{
    “error”: “invalid_user_password”,
    “error_description”: “Wrong email or verification code.”
}
```
version of lock ` compile 'com.auth0.android:lock:2.5.0'`
Can anybody help with this ?

**Comment by lbalmaceda** [comment]
@zfort-vitalii I can't reproduce it. The error message you get is because either the id (phone/email) or the code received doesn't match the server's expected one or has expired.
Btw.. You can set the scope with the builder:

```
PasswordlessLock mLock = PasswordlessLock.newBuilder(auth0, mCallback)
             .withAuthenticationParameters(params)
             .withAuthButtonSize(AuthButtonSize.SMALL)
             .withScope("openid profile")
             .useLink()
             .closable(true)
             .build(this);
```
Because the builder options are used when you call `mLock.newIntent(context)`, changing them after that line would not affect the first call. So avoid doing this `mLock.getOptions().withScope("openid profile");` and use the builder methods.
