### ISSUE TITLE
Failed authentication with LockActivity

### ISSUE THREAD

**Issue by KingIdee** [auth0/Lock.Android#440]
When i try logging in with user name and password, i get this error. Kindly note that I have enabled a database connection for client on the dashboard. Please find attached the logs.

09-22 14:23:44.504 3213-3513/com.idee.android_auth0_kotlin E/LockActivity: Failed to authenticate the user: An error occurred when trying to authenticate with the server.
                                                                           com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.

**Comment by lbalmaceda** [comment]
Unfortunately, that error doesn't say too much. Please enable HTTP logging by calling [auth0#setLoggingEnabled](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/Auth0.java#L203) on your `Auth0` instance.

**Comment by KingIdee** [comment]
This was the error
{"error":"unauthorized_client","error_description":"Grant type 'http://auth0.com/oauth/grant-type/password-realm' not allowed for the client.","error_uri":"https://auth0.com/docs/clients/client-grant-types"}

And I have fixed it using those links. But the documentation never told us

**Comment by lbalmaceda** [comment]
Apologies for that. Since a few months that grant is disabled by default for new clients. You're right, docs should be updated to show how to enable it 😞 . They do warn about the usage of embedded lock (this library). And we're also trying to encourage the use of [hosted web authentication](https://github.com/auth0/auth0.android#authentication-with-hosted-login-page) like we do [here](https://auth0.com/docs/quickstart/native/android/00-login#hosted-login-page-vs-embedded-login). 
I'll pass the feedback to the docs team and make sure to update this repo's readme to provide the notice for DB connections. If you don't mind, would you please share the docs/guides links you've followed that lead you to this issue? Thanks

**Comment by KingIdee** [comment]
Seriously, I have used about two different but similar documentations just to implement this. I particularly used [this](https://github.com/KingIdee/Lock.Android). Finally, why is the embedded Lock not recommended. That is the best approach for mobile apps. Taking them out of the app for authentication defeats the aim

**Comment by lbalmaceda** [comment]
In our latest release we added Chrome Custom Tabs to try to fight that feeling of leaving the app, but of course, that will only work for people who have a CCT enabled browser app installed, like chrome or firefox. People who don't have it will "leave the app" while the authentication is ongoing. 
The industry is moving towards webauth (google/facebook to name a few). All the pro/con on using one or the other are listed in a document here: https://auth0.com/docs/tutorials/browser-based-vs-native-experience-on-mobile.

**Comment by VictorGevondyan** [comment]
Yes, really, wasting 1 day , because of documentation lack. Though, to be honest, besides this point, Auth0 documentation is pretty good! :) . So, as I understand, we should not use Lock, and should use Android.Auth0. :)

**Comment by lbalmaceda** [comment]
@VictorGevondyan This behavior was clarified in this library's README [5 months ago](https://github.com/auth0/Lock.Android#notes-on-embedded-authentication). If you find an outdated article please don't hesitate to point it out so we can fix it.
