### ISSUE TITLE
Access token is null

### ISSUE THREAD

**Issue by KingIdee** [auth0/Lock.Android#442]
After a user is successfully authenticated, I try to access my refresh token using credentials.refreshToken but it is null, whereas Acess token is enabled in my grant types.

**Comment by lbalmaceda** [comment]
I think you're mixing some concepts. The refresh_token grant is needed in order to exchange a refresh_token for a new pair of tokens, but it's not needed to ask for a refresh_token. That grant is enabled by default by the way, and you should keep it that way. 

To obtain a refresh_token upon login you must request a `scope` that includes the `offline_access` value, like "openid offline_access". (openid is the scope requested by default). To do so in Lock you need to change the scope while building the lock instance. The rest remains the same.

```java
lock = Lock.newBuilder(account, callback)
      //Customize Lock
      .withScope("openid offline_access")
      .build(this);
```

Once you get the refresh_token, you can exchange it for new tokens by calling [this](https://github.com/auth0/Auth0.Android/blob/master/auth0/src/main/java/com/auth0/android/authentication/AuthenticationAPIClient.java#L683) method.

If you have further questions I suggest you visit https://support.auth0.com as GH issues is not our official support channel.
Cheers

**Comment by lenka073** [comment]
Proč se mi ukazuje na displeji ACCOUNT TOKEN is null a to pořád jak to mám zlikvidovat
