### ISSUE TITLE
Browser Cache issue with Lock.Android SDK - Not asking account selection from second time onwards

### ISSUE THREAD

**Issue by KetanPCoditas** [auth0/Lock.Android#475]
Hi there,

I am using Lock.Android SDK in application to perform login using Google. When I click on Google SignUp button, it performs login as expected. It asks to choose an account to perform login and does the rest.

The problem is that when I logged out of application and again try to perform login, it does not ask for an account to choose. In device, I have configured multiple accounts. So here, I am expecting that, Lock.Android SDK should ask which account will be used to perform login and based on account selection, it should proceed with login. I believe it takes account information from browser cache. 

How can I come over this issue? Is there any way in Lock.Android SDK, so every login it asks me to choose an account? Is there any option I can configure? 

I think in Lock.js, there is an option called "prompt" and when we provide value "none", it asks every time to choose an account. Is there anything similar in Lock.Android SDK?

Thanks.

**Comment by lbalmaceda** [comment]
@KetanPCoditas The parameter you're looking for is `prompt=login`. Send it on the authorize call and lock will ask for your account every time.

**Comment by KetanPCoditas** [comment]
@lbalmaceda Login with Facebook does not ask to use another account with `prompt=login`. Morever, I tried with `prompt=select_account` as well but no luck.

**Comment by lbalmaceda** [comment]
@KetanPCoditas I imagine that you're running into issues because you're as well passing `connection=facebook` as a parameter to that authorization call, which directly takes you to facebook site skipping the Universal Login Page. Any parameter that you send in the request ends up in the provider's login page as well. e.g. `prompt=login` is read by our Universal Login Page but also sent to facebook. It might be the case that the provider doesn't support that prompt or has a different name for it.
Checking the [provider's documentation](https://developers.facebook.com/docs/facebook-login/reauthentication/) they mention a way to force the authentication by passing `auth_type=reauthenticate`. I haven't tested though 👍

**Comment by KetanPCoditas** [comment]
Hi @lbalmaceda , It is not working. I am passing as below:

val authenticationParams: HashMap<String, Any> = HashMap()
authenticationParams["prompt"] = "login"
authenticationParams["auth_type"] = "reauthenticate"

... builder.withAuthenticationParameters(authenticationParams)

**Comment by lbalmaceda** [comment]
@KetanPCoditas You're doing it fine. But like I said, this is outside of this library's scope and the implementation of that behavior belongs to Facebook. Searching over google I found that this `auth_type=reauthenticate` parameter they have documented [seems to have stopped working](https://stackoverflow.com/questions/13289240/reauthenticate-feature-has-changed-its-behavior). You might want to reach them and ask for a way to re-authenticate.
