### ISSUE TITLE
Sign in and Sign up tabs are not changing correctly all the time

### ISSUE THREAD

**Issue by BesatZardoshtCarfax** [auth0/Lock.Android#573]
### Description

When switching between sign in and sign up tabs sometimes the tab does change but not the content of the page.

### Reproduction

- Click on sign in and sign out several times
<img width="318" alt="Screen Shot 2020-05-04 at 9 22 38 PM" src="https://user-images.githubusercontent.com/52752909/81027948-8f897e00-8e4d-11ea-901e-f4bd8eb49b28.png">
<img width="319" alt="Screen Shot 2020-05-04 at 9 23 41 PM" src="https://user-images.githubusercontent.com/52752909/81027951-91534180-8e4d-11ea-87ad-c46aa943257e.png">

### Environment

- implementation 'com.auth0.android:lock:2.19.0'

**Comment by lbalmaceda** [comment]
@BesatZardoshtCarfax Thanks! 

The form displays the right data, as I see the tab title getting its bold style. But the selected tab is not the correct one. 

The logic for updating that view is defined [here](https://github.com/auth0/Lock.Android/blob/master/lib/src/main/java/com/auth0/android/lock/views/ModeSelectionView.java#L84). If this is a sync issue we might need to wrap both selecting the tab and changing the font style around brackets.

In order to define the priority of this, I have a few questions. 
1. How fast are you changing tabs? 
2. Has this started to happen on this last release or is it also present on an old version?
3. Would you mind recording a short video?

**Comment by amankumar367** [comment]
@lbalmaceda ,

I'm also facing the same issue after resolving the issue of Tab height (Material Design version issue)

> How fast are you changing tabs?

Sometimes its also not working in slow tap

> Has this started to happen on this last release or is it also present on an old version?

Yes, After upgrading from `v2.18.0 to v2.19.0`. In the old version, there was no issue with tab changes.

> Would you mind recording a short video?

Please find the below GIF

![Auth0_Lock_Tab_change_issue](https://user-images.githubusercontent.com/35893342/81301093-3a8c7880-9096-11ea-83aa-1c9b8da4ed5c.gif)

**Comment by lbalmaceda** [comment]
Thanks for those details, Aman. I'll add this to our backlog and I'll ask the team if we can prioritize it for the coming week.
